In [2]:
import numpy as np
import torch

In [2]:
# 用于检验pytorch安装是否成功的常规操作
torch.__version__

'1.9.0a0+gitd69c22d'

In [3]:
# 创建Tensor的常用方式，常用于生成随机tensor作为输入测试搭好的神经网络模型内部是否维度匹配
torch.rand(5,3)

tensor([[0.8360, 0.9117, 0.7324],
        [0.2278, 0.6764, 0.2234],
        [0.6801, 0.9425, 0.5561],
        [0.0258, 0.2963, 0.0823],
        [0.7544, 0.7261, 0.4810]])

In [5]:
# 常用创建tensor的方式
x=torch.zeros(5,3,dtype=torch.long)# 创建全零张量，设置类型，还有其他可选torch.float64
x=torch.Tensor([5,3])# 把列表[5,3]转化为张量
y=x.new_ones(2,4)# 以x为模板创建一个2行4列的全1张量，这个张量与x有相同的torch.dtype和torch.device
z=torch.randn_like(x,dtype=torch.float64)# 创建与x相同尺寸随机数
x.size()# 获取tensor尺寸

torch.Size([2])

In [6]:
x=torch.randn(1)
print(x.item())# Tensor元素只有一个的时候用于获取Tensor的值

-1.1860140562057495


In [7]:
x=torch.randn(2,2)
y=torch.randn(2,2)
z = torch.add(x,y)# 加法

Tensor可以理解为一个变量，也就是说当创建一个Tensor(1)的时候，最后理解成创建了一个自变量x，x的取值为1，这样方便理解对该张量的求导，比如最后它与张量Tensor(2)相乘，就可以理解成另一个自变量y它相乘，得到函数z=x*y，这时候对Tensor(1)求导即为z对x求导，导数是y，而y=2，所以该导数为2

In [11]:
x=torch.randn(5,3)
z=x.view(15)# view函数得到的变量和x是共享内存的，也就是它们其实指向同一个Tensor，只不过观察角度不同
z1=x.view(-1,5)
print(x)
print(z)# z是把x按行观察变成一个行向量
print(z1)# view第一个参数-1说明按张量尺寸确定，第二个参数5说明列必须是5列

tensor([[-1.4969,  0.3869,  0.1799],
        [-0.2547,  0.6612,  0.5817],
        [-0.1369,  1.0073, -0.4423],
        [ 0.3169,  1.4155,  0.8150],
        [ 0.0336,  0.6081, -1.0811]])
tensor([-1.4969,  0.3869,  0.1799, -0.2547,  0.6612,  0.5817, -0.1369,  1.0073,
        -0.4423,  0.3169,  1.4155,  0.8150,  0.0336,  0.6081, -1.0811])
tensor([[-1.4969,  0.3869,  0.1799, -0.2547,  0.6612],
        [ 0.5817, -0.1369,  1.0073, -0.4423,  0.3169],
        [ 1.4155,  0.8150,  0.0336,  0.6081, -1.0811]])


In [12]:
# 不同尺寸的Tensor相加时会自动触发广播机制，也就是尺寸向大尺寸对齐
# 1）数组看齐维度最长的数组，维度不足部分在前加1补齐
# 2）运算后的数组维度是所有数组维度的最大值
# 3）输入数组的某个维度和输出数组的对应维度长度相同或长度为1，则数组可以计算，否则会出错
# 4）输入数组某维度长度为1时，其他维度都用这一维度的值
x=torch.arange(1,4).view(1,3)# 生成[1,4)的数
y=torch.arange(1,5).view(4,1)
print(x)
print(y)
print(x+y)

tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6],
        [5, 6, 7]])


In [14]:
x=torch.ones(5,3)
y=x.numpy()# 采用numpy方法将x转为numpy，二者内存共享
print('x=',x)
print('y=',y)
x+=1
print('x=',x)
print('y=',y)# 可以发现我们只对x加1，但是y也随之改变，这是因为二者是共享内存的
z=torch.from_numpy(y)# 该方法可以将numpy转Tensor，同样的，转出来的结果也共享内存
z+=1
print('x=',x)# 可以发现只对z加1，x的值却变了

x= tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
y= [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
x= tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
y= [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
x= tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])


In [16]:
# pytorch在CPU和GPU的应用
x=torch.randn(3,5)
if torch.cuda.is_available():# 用于判断cuda是否可见和可用的常用判断
    device=torch.device('cuda')# cuda设备设置
    y=torch.ones_like(x,device=device)# 直接在device的GPU上创建Tensor
    x=x.to(device)# 把x移动到cuda
    z=x+y
    print(z)

tensor([[ 2.6977,  0.1552,  0.3303,  1.2030,  1.5942],
        [ 0.6315,  1.3783,  2.1998,  0.5334,  1.2236],
        [ 1.0338,  1.3130,  0.3557, -0.7227,  1.2405]], device='cuda:0')


In [18]:
# 自动求解梯度
x=torch.randn(5,3,requires_grad=True)# 创建一个需要追踪梯度的张量
# 这个用于查看创建该Tensor的Function（CalculateGraph.py有介绍这个函数），说明该变量是从哪个运算得到的
# 由于我们直接创建，所以它是None
print(x.grad_fn)
y=x+1
print(y.grad_fn)# y是自变量x加上常数得到的，通过加法创建

None


In [22]:
# 修改张量求解梯度与否
x=torch.randn(5,3)
y=(x*3)/(x-1)# 默认创建时没有跟踪梯度
print('grad of x=',x.requires_grad)
x.requires_grad_(True)# 跟踪梯度
z=(x*x).sum()# y可用求导
print('grad of z=',z.requires_grad)

grad of x= False
grad of z= True


In [23]:
# 对上面的z求梯度
z.backward()
# x*x的导数是2*x，此时x已经有了梯度
print('x=',x)
print('x grad=',x.grad)

x= tensor([[-0.4376,  1.3637,  0.3737],
        [-1.2171,  0.4182,  0.8781],
        [-0.1474,  0.8405, -1.4764],
        [-0.1416, -1.6874,  0.6844],
        [-0.0931, -1.3720, -0.3416]], requires_grad=True)
x grad= tensor([[-0.8751,  2.7275,  0.7475],
        [-2.4343,  0.8363,  1.7562],
        [-0.2948,  1.6810, -2.9527],
        [-0.2833, -3.3747,  1.3688],
        [-0.1863, -2.7440, -0.6833]])


In [26]:
x=torch.rand(5,3,requires_grad=True)
print('x**2 require grad=',(x**2).requires_grad)
with torch.no_grad():
    print('x**2 require grad=',(x**2).requires_grad)# 用代码段以停止跟踪x接下来的运算的梯度
    print('x require grad=',x.requires_grad)# 注意只是不跟踪x的运算的梯度，x的梯度还在


x**2 require grad= True
x**2 require grad= False
x require grad= True


# 文献7中的pytorch编程基础

In [3]:
# 使用基本的numpy
# 创建对角矩阵
v = np.array([1,8,4])
np.diag(v)

array([[1, 0, 0],
       [0, 8, 0],
       [0, 0, 4]])

In [4]:
np.eye(3)# 创建单元矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.array(range(4)).reshape(2,2)
b = np.array(range(4,8)).reshape(2,2)
print(a*b)# 哈达玛积
print(a@b)# 点积
print(np.dot(a,b))# 点积
ma = np.asmatrix(a)
mb = np.asmatrix(b)
print(ma*mb)

In [ ]:
# 对角矩阵特性
a = np.diag([1,2,3])
print(a)
v,e = np.linalg.eig(a)# 计算特征值和特征向量
print(v)# 特征值，对角矩阵特征值就是其对角
print(e)
print(a@a@a)# 对角矩阵哈达玛积跟点积一样的结果
print(np.linalg.inv(a))# 取逆
print(np.matrix(a).I)# 转矩阵以后可直接取逆

In [ ]:
# 创建张量
a = torch.tensor(5)# 创建单个张量
print(a)
anp = np.asarray([4])
a = torch.tensor(anp)
print(a)
# 注意torch.Tensor和torch.tensor使用的区别
a = torch.Tensor(5)# 这个指定的是尺寸而非内容，张量有值但是其实算没有初始化的
print(a)
a = torch.Tensor(1,2)# 这个也指定的是尺寸而非内容
print(a)
a = torch.Tensor([5])# 这个指定的是内容
print(a)
# 如果想指定随机初始化值
x = torch.rand(2,1)
print(x)
zero = torch.zeros_like(x)# 生成与x形状且类型一样的0张量，类似的还有ones_like
print(zero)
eye = torch.eye(2)# 对角矩阵
print(eye)
full = torch.full((2,2),3)# 前一个参数是尺寸，后1个是值
print(full)

In [ ]:
# 设置默认的张量类型
print(torch.get_default_dtype())
print(torch.Tensor([1,3]).dtype)
torch.set_default_dtype(torch.float64)
print(torch.get_default_dtype())
print(torch.Tensor([1,3]).dtype)

In [17]:
# 生成随机张量
print(torch.initial_seed())
torch.manual_seed(2022)
torch.initial_seed()

16454425952403744961


2022

In [20]:
# 随机生成张量
print(torch.randn(2,3))# 指定生成尺寸
print(torch.arange(1,10,step=2))# 线性空间随机值，半闭半开区间，按步长取数
print(torch.linspace(1,9,steps=5))# 线性空间随机值，闭区间，取step个数
print(torch.logspace(1,9,steps=5))# 对数空间随机值
print(torch.empty(1,2))# 生成未初始化矩阵

tensor([[ 0.1110,  0.2050,  0.0333],
        [-1.0556, -0.5344,  1.2262]])
tensor([1, 3, 5, 7, 9])
tensor([1., 3., 5., 7., 9.])
tensor([1.0000e+01, 1.0000e+03, 1.0000e+05, 1.0000e+07, 1.0000e+09])
tensor([[5.2290e-316, 5.2276e-316]])


In [24]:
a = torch.Tensor(2)
print(a)
print(torch.numel(a))# 取出a中元素的个数2
print(torch.is_tensor(a))# 判断是不是张量
a = torch.FloatTensor([4])
print(a.type(torch.IntTensor)) # 修改tensor类型
print(a.type(torch.DoubleTensor))
print(a.int())# 数值张量可以用类似这种写法
print(a.double())

tensor([6.9402e-310, 5.1747e-316])
2
True
tensor([4], dtype=torch.int32)
tensor([4.])
tensor([4], dtype=torch.int32)
tensor([4.])


In [28]:
# 运算重载
a = torch.FloatTensor([4])
print(a)
b = torch.add(a,a)
print(b)
# 自变化函数
a.add_(b)# a+=b
print(a)
# pytorch所有的自变化函数都会带有下划线，如x.copy_(y)
print(a.mean())
print(a.sqrt())

tensor([4.], dtype=torch.float32)
tensor([8.], dtype=torch.float32)
tensor([12.], dtype=torch.float32)
tensor(12., dtype=torch.float32)
tensor([3.4641], dtype=torch.float32)


In [ ]:
# 张量与numpy互换
a = torch.FloatTensor([4])
print(a.numpy())# 张量转numpy
anp = np.asarray([4])
print(torch.from_numpy(anp))# numpy转tensor
print(torch.tensor(anp))# numpy转tensor
# 张量与numpy各自形状获取
x = torch.rand(2,1)
print(x.shape)
print(x.size())
anp = np.asarray([4,2])
print(anp.size,anp.shape)
print(x.reshape([1,2]).shape)# 修改形状

In [32]:
# 注意：numpy在转换成张量以后两个变量共享同一块内存，其中一个变量的改变会影响另一个值
# pytorch内部实现时，numpy转张量后，如果张量改动，会出发复制机制，不会改变numpy值
# 但是numpy转张量以后对numpy修改，由于numpy没有这种机制，所以会导致tensor也变化
nparray = np.array([1,1])
x = torch.from_numpy(nparray)# x来自于nparray，内存共享
print(x)
nparray+=1# 修改的是nparray
print(x)# x却改变了
nparray = nparray+1# 这次也改变了nparray
print(x)#但是x没有改变，这是因为上一行执行时候是复制了一个内存存储nparray+1的值


tensor([1, 1])
tensor([2, 2])
tensor([2, 2])


In [35]:
# 在cpu和gpu中定义张量
a = torch.FloatTensor([4])
b = a.cuda()
print(b)
print(b.cpu())# 移动数据
a = torch.tensor([4],device='cuda:0')# 直接调用,此时只能用tensor方法创建
print(a)
a = torch.FloatTensor([4])
print(a.to("cuda:0"))
import os
os.environ['CUDA_VISIBLE_DEVICES']="0"# 定义gpu环境

tensor([4.], device='cuda:0', dtype=torch.float32)
tensor([4.], dtype=torch.float32)
tensor([4], device='cuda:0')
tensor([4.], device='cuda:0', dtype=torch.float32)


In [37]:
# 张量维度变化
a = torch.tensor([[1,2],[3,4]])
b = torch.reshape(a,(1,-1))
print(b.shape)
c = torch.unsqueeze(b,dim=0)# 增加值为1的维度
print(c.shape)
print(torch.squeeze(c,dim=0).shape)# 消除值为1的维度

torch.Size([1, 4])
torch.Size([1, 1, 4])
torch.Size([1, 4])


In [ ]:
# 矩阵转置
b = torch.tensor([[5,6,7],[2,8,0]])
print(torch.t(b))
print(b.permute(1,0))# 维度0和1交换

In [39]:
# 张量的维度变化
# view方法只能操作连续内存的张量，permute或transpose以后的张量内存可能被修改
# 可以用is_contiguous方法判断内存是否连续，用contiguous方法使内存连续
b = torch.tensor([[5,6,7],[2,8,0]])
print(b.is_contiguous())
c = b.transpose(0,1)
print(c.is_contiguous())
print(c.contiguous().is_contiguous())
print(c.contiguous().view(-1))

True
False
True
tensor([5, 2, 6, 8, 7, 0])


In [ ]:
# 张量连接
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
print(torch.cat([a,b],dim=0))
print(torch.cat([a,b],dim=1))
# 张量切割
print(torch.chunk(a,chunks=2,dim=0))# 沿着0维度切成两份
print(torch.chunk(a,chunks=2,dim=1))
# 张量不均匀切割
b = torch.tensor([[5,6,7],[2,8,0]])
print(torch.split(b,split_size_or_sections=(1,2),dim=1))# 将b沿着1维度切成两部分

In [45]:
# 数据检索
b = torch.tensor([[5,6,7],[2,8,0]])
print(torch.gather(b,dim=1,index=torch.tensor([[1,0],[1,2]])))# 维持维度1按index输出
print(torch.gather(b,dim=0,index=torch.tensor([[1,0,0]])))# 维持维度0按index输出
# 如果要取整行可以用index_select
print(torch.index_select(b,dim=0,index=torch.tensor(1)))# 维持维度0大小不变，取每个其他维度idx=1的值

tensor([[6, 5],
        [8, 0]])
tensor([[2, 6, 7]])
tensor([[2, 8, 0]])


In [3]:
a = torch.tensor([[1,2],[3,4]])
mask = a.ge(2)# 大于等于ge 大于gt 小于等于le 小于lt
print(mask)
torch.masked_select(a,mask)

tensor([[False,  True],
        [ True,  True]])


tensor([2, 3, 4])

In [4]:
# 条件张量取值
b = torch.tensor([[5,6,7],[2,8,0]])
c = torch.ones_like(b)
print(c)
torch.where(b>5,b,c)# 条件满足选b不满足选c

tensor([[1, 1, 1],
        [1, 1, 1]])


tensor([[1, 6, 7],
        [1, 8, 1]])

In [5]:
# 阈值截断
a = torch.tensor([[1,2],[3,4]])
torch.clamp(a,min=2,max=3)

tensor([[2, 2],
        [3, 3]])

In [9]:
# 获取最值索引
a = torch.tensor([[7,2,5,8],[3,4,1,6]])
print(torch.argmax(a,dim=0))# 维持0维大小
print(torch.argmin(a,dim=0))
print(torch.max(a,dim=0))

tensor([0, 1, 0, 0])
tensor([1, 0, 1, 1])
torch.return_types.max(
values=tensor([7, 4, 5, 8]),
indices=tensor([0, 1, 0, 0]))


In [10]:
# 求导机制
x = torch.tensor([1.],requires_grad=True)# 跟踪梯度
with torch.no_grad():
    y=x*2
print(y.requires_grad)
#@torch.no_grad()装饰器可以对函数实现这种功能
# 激活梯度则为torch.enable_grad
# 统一管理torch.set_grad_enable()

False


In [16]:
# 张量计算图
x = torch.rand(2,2,requires_grad=True)
print(x,x.grad_fn)# grad_fn保存梯度，由于使叶子节点 没有梯度
m = x+2
print(m.grad_fn)# 具有fn属性
print(m.grad_fn(x))# 对x的导数
print(m.is_leaf)# 是否叶子节点
print(x.is_leaf)
f=m.mean()
f.backward()#求导
print(f,x.grad)#grad保存梯度值
m.detach().numpy()#从图中分离转numpy

tensor([[0.6189, 0.9817],
        [0.3301, 0.9969]], requires_grad=True) None
(tensor([[0.6189, 0.9817],
        [0.3301, 0.9969]], requires_grad=True), None)
False
True
tensor(2.7319, grad_fn=<MeanBackward0>) tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


array([[2.6189387, 2.9817467],
       [2.330052 , 2.9968555]], dtype=float32)